---
kind: pipeline
type: docker
name: default

trigger:
  event:
  - pull_request

steps:
- name: test
  image: node:10
  commands:
  - npm test

---
kind: pipeline
type: docker
name: merge_to_master

trigger:
  branch:
  - master
  event:
  - push

steps:
- name: build
  image: node:10
  commands:
  - npm i -g gatsby-cli
  - npm i 
  - gatsby build
