---
kind: pipeline
type: docker
name: default

trigger:
  event:
  - pull_request

steps:
- name: test
  image: node:10
  commands:
  - npm test

---
kind: pipeline
type: docker
name: merge_to_master

trigger:
  branch:
  - master
  event:
  - push

steps:
- name: build
  image: node:10
  commands:
  - npm i -g gatsby-cli
  - npm i 
  - gatsby build

- name: deploy-sync-invalidate-cache
  image: plugins/s3-sync:1
  settings:
    bucket: website-nille-dev
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    region: eu-north-1
    bucket: website-nille-dev
    source: public/
    target: /
    delete: true
    cloudfront_distribution: E358FDGEVL9W5T

- name: notify-slack
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: notifications
    icon_url: https://cdn.iconscout.com/icon/free/png-256/github-153-675523.png
    template: >
      {{#success build.status}}
         {{build.link}} Build {{build.number}} succeeded. Good job.
      {{else}}
        {{build.link}} Build {{build.number}} failed. Fix me please. 
      {{/success}}
