---
kind: pipeline
type: docker
name: default

trigger:
  event:
  - pull_request

steps:
- name: test
  image: node:10
  commands:
  - npm test

---
kind: pipeline
type: docker
name: merge_to_master

trigger:
  branch:
  - master
  event:
  - push

steps:
- name: build
  image: node:10
  commands:
  - npm i -g gatsby-cli
  - npm i 
  - gatsby build

- name: deploy
  image: plugins/s3
  settings:
    bucket: website-nille-dev
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    source: public/public/*
    target: /
    region: eu-north-1

- name: invalidate-cloudfront-cache
  image: tozny/cloudfront-invalidation 
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: eu-north-1
    DISTRIBUTION_ID: E358FDGEVL9W5T
